name: GitHub Release Download
author: acst
description: Downloads a GitHub release from a repository and can add folders to the path
inputs:
  owner:
    description: GitHub owner the repository exists in
    required: false
    default: acst
  repo:
    description: GitHub repository to get the release from (defaults to the value of the tool argument)
    required: false
  tag:
    description: Which tag of the release to download
    required: false
    default: latest
  tool:
    description: Tool to download. This is used to determine the release artifact name
    required: true
  github_token:
    description: Token used to download releases from private repositories
    required: true
  bin:
    description: Location of the directory to add to PATH
    required: false
  release_format:
    description: The format of the release file without the extension
    required: false
    default: $TOOL-$OS-$ARCH
  has_root_folder:
    description: Is the release compressed with a root folder in it (a folder with the same name as the compressed filename).
    required: false
    default: false
outputs:
  download_path:
    description: Location of the uncompressed files
runs:
  using: node12
  main: lib/index.js
branding:
  color: purple
  icon: download
